baseurl = "https://techblog.lol/"
languageCode = "en-us"
title = "techblog.lol"
theme = "hyde-x"
paginate = 10

[params]
    truncate = true

    defaultDescription = "This is our techblog. lol."
    defaultKeywords = "tech,blog,techblog,lol"

    theme = "theme-base-00"

    highlight = "sunburst"

    tagline = "This is our techblog. lol."

    home = "Techblog"

    github = "https://github.com/techbloglol/techblog.lol"

    rss = true

[taxonomies]
    tag = "tags"
